export const GET_LIST_STAR_SHIP = "GET_LIST_STAR_SHIP";
export const SET_SELECTED_RANDOM_CARD = "SET_SELECTED_RANDOM_CARD";
export const SET_HIDDEN_RANDOM_CARD = "SET_HIDDEN_RANDOM_CARD";
export const SET_TOTAL_TURN = "SET_TOTAL_TURN";
export const SET_SCORE_GAME = "SET_SCORE_GAME";
